[package]
name = "wolfeymetrics"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13.3"
tokio = { version = "1.40.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "tracing",
] }
serde = { version = "1.0.210", features = ["derive"] }
chrono = "0.4.38"
num_cpus = "1.16.0"
dashmap = { version = "6.1.0", features = ["inline", "serde"] }


[build-dependencies]
tonic-build = "0.12"
